### ISSUE TITLE
个人觉得代码还有有极大改善空间的

### ISSUE THREAD

**Issue by sweetalin** [mission008/shopweb#1]
代码有规范吗？
数据库有连接吗？
分层够详细吗？
有对自己代码负责的态度吗？

**Comment by JosanSun** [comment]
这个跟电子科大有毛关系？
别人开源自己项目，你直接喷，你自己做了什么？
You can you up, no can no bb

**Comment by sweetalin** [comment]
抱歉，去年的这条言论引发了你的不适。
